export default {
    LOAD_BOARD_FETCHING: 'REDUX_THUNK_LOAD_BOARD_FETCHING',
    LOAD_BOARD_SUCCESS: 'REDUX_THUNK_LOAD_BOARD_SUCCESS',
    LOAD_BOARD_ERROR: 'REDUX_THUNK_LOAD_BOARD_ERROR',

    CHANGE_BOARD_NAME_UPDATING: 'CHANGE_BOARD_NAME_UPDATING',
    CHANGE_BOARD_NAME_SUCCESS: 'CHANGE_BOARD_NAME_UPDATING',
    CHANGE_BOARD_NAME_ERROR: 'CHANGE_BOARD_NAME_UPDATING',

    CHANGE_COLUMN_NAME_UPDATING: 'CHANGE_COLUMN_NAME_UPDATING',
    CHANGE_COLUMN_NAME_ERROR: 'CHANGE_COLUMN_NAME_ERROR',
    CHANGE_COLUMN_NAME_SUCCESS: 'CHANGE_COLUMN_NAME_SUCCESS',

    CHANGE_TASK_NAME_UPDATING: 'CHANGE_COLUMN_NAME_UPDATING',
    CHANGE_TASK_NAME_ERROR: 'CHANGE_COLUMN_NAME_ERROR',
    CHANGE_TASK_NAME_SUCCESS: 'CHANGE_COLUMN_NAME_SUCCESS',

    ADD_COLUMN_PROCESSING: 'ADD_COLUMN_PROCESSING',
    ADD_COLUMN_SUCCESS: 'ADD_COLUMN_SUCCESS',
    ADD_COLUMN_ERROR: 'ADD_COLUMN_ERROR',

    ADD_TASK_PROCESSING: 'ADD_TASK_PROCESSING',
    ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
    ADD_TASK_ERROR: 'ADD_TASK_ERROR',

    DELETE_COLUMN_PROCESSING: 'DELETE_COLUMN_PROCESSING',
    DELETE_COLUMN_DELETING_START: 'DELETE_COLUMN_DELETING_START',
    DELETE_COLUMN_SUCCESS: 'DELETE_COLUMN_SUCCESS',
    DELETE_COLUMN_ERROR: 'DELETE_COLUMN_ERROR',
    SET_DELETING_STATE_COLUMN: 'SET_DELETING_STATE_COLUMN',

    DELETE_TASK_PROCESSING: 'DELETE_TASK_PROCESSING',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
    SET_DELETING_STATE_TASK: 'SET_DELETING_STATE_TASK'
}