export const LOAD_BOARD_FETCHING = 'REDUX_THUNK_LOAD_BOARD_FETCHING';
export const LOAD_BOARD_SUCCESS = 'REDUX_THUNK_LOAD_BOARD_SUCCESS';
export const LOAD_BOARD_ERROR = 'REDUX_THUNK_LOAD_BOARD_ERROR';
export const CHANGE_BOARD_NAME_UPDATING = 'CHANGE_BOARD_NAME_UPDATING';
export const CHANGE_BOARD_NAME_SUCCESS = 'CHANGE_BOARD_NAME_UPDATING';
export const CHANGE_BOARD_NAME_ERROR = 'CHANGE_BOARD_NAME_UPDATING';